# Built with Jekyll 3.6.0

# Setup
title: 'MOUND.'
description: 'the mound...'
url: ''
baseurl: '/mound-jekyll'

# About/contact
author: ''
  name: ''
  url: ''
  email: ''

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections
collections:
  projects:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

remote_theme: minicomp/ed
